---
title: "data-day2-analyses"
author: "Jamil Bhanji and Vanessa Lobue"
date: "12/1/2022"
output: html_document
---

#### set up: set root directory and specify packages ("tidyverse")  
```{r setup, include=TRUE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
#command to change data viewing preference to show more columns in the data viewer:
rstudioapi::writeRStudioPreference("data_viewer_max_columns", 500L)
```

*thanks to Darian for volunteering data!!!*  

#### Import data and data dictionary from tab-delimited file 
- and set variable types  
```{r import-data, include=TRUE}
# read data and data dictionary
dr_tib <- readr::read_delim("data/2022/Darian-Raizberg-DataSet.txt",
                              delim = "\t")
dr_dict <- readr::read_delim("data/2022/Darian-Raizberg-Data-Dictionary.txt", delim = "\t")
#recode Test_setting, Group, accuracy, choice variables as factors
dr_tib <- dr_tib %>% mutate(
    Test_setting = factor(Test_setting, labels = c("in-person","online")),
    Group = factor(Group, labels = c("high effort","low effort","no effort")),
    Part2_Phase1_acc = factor(Part2_Phase1_acc, labels = c("incorrect","correct")),
    Part2_Phase2_acc = factor(Part2_Phase2_acc, labels = c("incorrect","correct")),
    Part2_Phase3_acc = factor(Part2_Phase3_acc, labels = c("incorrect","correct")),
    Part2_Phase2_fdbk_choice = factor(Part2_Phase2_fdbk_choice, 
                                      labels = c("not chosen","chosen"))
  ) 
sapply(dr_tib,class) %>%  knitr::kable(caption = "variable names and types") %>% 
  kableExtra::kable_styling()
```


### Aggregate across trials of the same type    
- Data consist of many trials per subject   

```{r aggregate-vis, results='hold', fig.show='hold'}
# first group by participants and store in new tibble
dr_aggbysub_tib <- dr_tib %>%
  drop_na(Part2_Phase2_acc,Part2_Phase3_acc,Part2_Phase2_fdbk_choice) %>% 
  group_by(Subj_ID,Test_setting,Group) %>% 
  summarise (
    numtrials = sum(Part2_Phase2_fdbk_choice=="chosen"|Part2_Phase2_fdbk_choice=="not chosen"),
    fdbk_choice_prop = sum(Part2_Phase2_fdbk_choice=="chosen")/numtrials,
    Part2_Phase2_acc_prop = sum(Part2_Phase2_acc=="correct")/numtrials,
    Part2_Phase3_acc_prop = sum(Part2_Phase3_acc=="correct")/numtrials,
    Part2_Phase2_conf_subjmean = mean(Part2_Phase2_conf)
    #also RT?
    #Part2_Phase2_RT_subjmean = mean(Part2_Phase2_RT)
  ) %>% ungroup()
# then print table of means, etc across participants, 
dr_aggbysub_tib %>% select(numtrials:last_col()) %>% 
  psych::describe() %>% knitr::kable(caption = "Whole sample descriptives", digits = 2) %>% 
  kableExtra::kable_classic(lightable_options = "hover")

# data visualization for relevant vars
p1 <- dr_aggbysub_tib %>% #drop_na() %>%
  ggplot( aes(x=fdbk_choice_prop)) + 
    geom_histogram(position = "identity", binwidth = .05, alpha = .25) + 
    theme_classic() + labs (title = "fdbk_choice_prop histogram")
p1
p2 <- dr_aggbysub_tib %>% #drop_na() %>%
  ggplot( aes(y=fdbk_choice_prop, x = Test_setting:Group)) + 
    geom_boxplot() + 
    theme_classic() +labs (title = "fdbk_choice_prop box plot")
p2
p3 <- dr_aggbysub_tib %>% #drop_na() %>%
  ggplot( aes(sample=fdbk_choice_prop)) + 
    geom_qq() + geom_qq_line() + 
    theme_classic() + labs (title = "fdbk_choice_prop box plot")
p3
```


### 2x2 Anova (between subjects)  

```{r two-by-two, results='hold', fig.show='hold'}

card_afx <- afex::aov_4(card_out_react_prep ~ emoreg_cond*direct_cond + (1|Sbj_ID), data = emo_tib)

```

