* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
MIXED RT BY modality
  /FIXED=modality | SSTYPE(3)
  /METHOD=ML
  /PRINT=SOLUTION TESTCOV
  /RANDOM=INTERCEPT | SUBJECT(PID) COVTYPE(VC)
  /RANDOM=INTERCEPT | SUBJECT(stim) COVTYPE(VC).
