---
title: "Activity-Read data and examine distributions"
author: "JB"
date: "2/16/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(readr)
library(ggplot2)
```

------------------------------------------------------------------------

*jb notes on potential lab formats*

Option 1. *first walk through a brief example that is highly related to the activity (but not the same). Then students work through the lab guide, with instructors providing guidance as needed. Solutions could be provided immediately or not.*

Option 2. *just direct students to necessary resources (lab guide, documentation for necessary functions), then walk the room to help with problems, provide explanation, etc*

------------------------------------------------------------------------

## Learning Objectives

-   Set up a project directory and create an R markdown file (\*.Rmd) to document your work

-   Read data from different file formats

-   Examine variables and characterize their distributions using simple visuals:

    -   histogram

    -   quantile-quantile plot

    -   (***jbnote - include a normality test such as shapiro-wilk?***)

------------------------------------------------------------------------

## Step 1 - Get organized.

[Video resource (Prof Andy Field) - Working in RStudio](http://milton-the-cat.rocks/learnr/r/r_getting_started/#section-working-in-rstudio) - watch the video if you want a review

#### 1.1 Set up a typical project work flow consisting of a project folder containing:

-   \*.Rproj file

-   "r_docs" folder to store your lab notes in R markdown

-   "data" folder to store data files for this activity

-   "images" folder to store plots

#### 1.2 Start a new R markdown document to save your work on this activity

-   name it something sensible

-   in the "setup" code chunk load these packages with the `library()` function:

    -   tidyverse, readr, ggplot2

-   also in the "setup" chunk, paste in the line below (sets the base directory for knitr):

    -   `knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())`

-   run the setup chunk (click the play button in the top right of the chunk) - this action will load the libraries that will be used below

    -   if you get an error that "there is no package called blahblahblah" then you either have a typo (remember R is case-sensitive), or you need to install the package (in the console type, e.g., `install.packages("tidyverse")` or use the "Tools" menu)

## Step 2 - Import datasets for this activity

#### 2.1 download the files ["ice_bucket.csv"](../data/icebucket.csv) and ["nhanes_selectvars_n500.csv"](../data/nhanes_selectvars_n500.csv)(right-click, save as) and move it to the "data" folder in your project

Here's a description of the ice bucket data from [Andy Field's discovr tutorial 02](https://www.discovr.rocks/discovr/):\
*The ice bucket challenge generated something like 2.3 million videos on YouTube. The data are stored in a csv file, which contains one variable **upload_day** that is the number of days after Chris Kennedy's initial challenge that each of 2,323,452 ice bucket related videos were uploaded to YouTube. For example, if the value is 21 it means that the video was uploaded 21 days after Chris Kennedy's initial challenge.*

Here is a link to [description of the NHANES variables in the full dataset](https://www.rdocumentation.org/packages/NHANES/versions/2.1.0/topics/NHANES) - you are going to work with a small subset of cases and variables

#### 2.2 Read the ice bucket data and NHANES data into R

-   put the code to read the files in a new code chunk (name it "Step2-load-datasets within your markdown file

-   if you need a reminder of the readr function, use File-\>Import Dataset-\>From text (readr) to generate the code through the RStudio menu

-   Workflow : Insert a "code chunk" into your R markdown doc and put the code there, then **use the "play" button to run chunks of code as you go along**. Don't "knit" the file until you want to see all your work in one html/pdf doc.

-   **Don't use the View() function in any of your markdown code chunks**- it will make "knitr" stall when you try to knit your final doc. Instead, just click on the variable in your environment window to look at the dataframe/tibble.

## Step 3 - Examine ice bucket data - frequency distribution

#### 3.1 Check out the frequency distribution of "upload_day"

3.1.2 Start a new code chunk called "3-ice-bucket-histogram". Make a histogram using ggplot geom_histogram() with no arguments (leaving defaults). What does the warning message say? (Write your notes above the code chunk)

3.1.3 Now, in the same code chunk, make the histogram again but set it to have 1 bin for each value of upload_day (you can use the `bins=`, `binwidth=`, or `breaks=` arguments in geom_histogram)

3.1.4 In the same code chunk, make the histogram again but set it to have 1 bin for upload_day values 20-29, 1 bin for values 30-39, ...

3.1.5 In your notes above the code chunk, describe the modality (how many peaks) and skew of the distribution.

3.1.6 Go back and give each plot a descriptive title, using `+ labs(title="my title")` in your code


## Step 4 - Examine NHANES data - outliers

#### 4.1 Check out the distribution of "Height" - insert a code chunk (below the previous one) and put your notes above it

-   You already loaded the dataset in Step 2, do you see it in your environment?

-   Plot a histogram and a boxplot of Height (pick a sensible bin setting).

-   Describe the distribution shape in your own words. Why does the boxplot show so many outliers at low values?

-   Make a quantile-quantile plot of Height. Is Height normally distributed in this sample?

-   **jbnote - include shapiro-wilk statistic here?**


#### 4.2 Filter by Age - insert a new code chunk (below the previous one) and put your notes above it

-   Now let's restrict the plots to individuals age 18 or older, make a new histogram, box plot, and q-q plot of height using just those individuals (you can use the filter() or subset() function). Describe the distribution again in your own words.

-   **jbnote - if shapiro-wilk is included above, have them redo it**


#### 4.3 Mini-challenge

-   Now make a histogram and boxplot of Height, but group by Gender, so that you have 1 histogram plot (where different Genders get color-coded) and 1 boxplot (with Gender on the x-axis). Do you see any outliers (according to the boxplot threshold), when the data are split by Gender?

-   Hints:

    -   you can use the "fill" argument in `aes()`to map a variable onto the fill color chart component (called an "aesthetic" in ggplot language) - use position="identity" and alpha=.5 so that the histogram bars for different Gender are overlayed (rather than stacked)

    -   you can use the "x" axis argument in aes() to map a variable onto the x-axis (for the boxplot)

-   **Things to pay attention to:** did you see a warning like "Removed {X} rows containing non-finite values" above the plots? What does that mean? How can you adjust your code so that you don't get the warning?

-   Experiment with different settings (position, alpha, theme) if you finish early

