---
title: "Data Visualization in R - basic examples"
output:
  html_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(readr)
library(ggplot2)
```

------------------------------------------------------------------------

## Learning Objectives

-   Learn some things

    -   thing 1
    -   thing 2
    -   *challenge section* - extra things

-   References:
    -   if any

------------------------------------------------------------------------


### Starting off notes  


## Step 1 - Get organized
- make a folder for today's activity, with a new Rproj file  
- make a "data" folder  
  - **Download the data file [mentalrotation.csv](../data/mentalrotation.csv)** and place it in the new "data" folder  
- make a "r_docs" folder  
  - start a new R Markdown doc and save it in your r_docs folder  

------------------------------------------------------------------------

## Step 2 - Import data and check it out  

- data description if needed 
- **What to do first:** Make a new code chunk and use readr::read_csv() to read in the data. Make sure that NA values are handled the way you want (click on the tibble in the Environment window pane to take a quick look).   
- **What to do next:** make sure the columns that contain nominal vals are treated as nominal, using forcats::as_factor()  *take a look at the solution to see how*

<button class="btn btn-primary" data-toggle="collapse" data-target="#step-2"> Show/Hide Solution </button>  
<div id="step-2" class="collapse">  
```{r Step-2-import, fig.show='hold', results='hold', message=FALSE}
#first import the data
mrot_tib <- readr::read_csv("data/mentalrotation.csv", na = "NA")

# now make sure the columns we want as factors are treated that way, using forcats::as_factor() - we could let "Angle" be a Ratio variable 
mrot_tib <- mrot_tib %>% dplyr::mutate(
  DesiredResponse = forcats::as_factor(DesiredResponse),
  ActualResponse = forcats::as_factor(ActualResponse),
  CorrectResponse = forcats::as_factor(CorrectResponse),
  Sex = forcats::as_factor(Sex),
)
```
</div>
&nbsp;

- **Now skip some things you would normally do:** If you want to take a look at descriptives and distribution of response time, click the button:  
  
<button class="btn btn-primary" data-toggle="collapse" data-target="#vis2a"> Show/Hide Extra Stuff </button>  
<div id="vis2a" class="collapse">  
```{r Step-2a-examine, fig.show='hold', results='hold', message=FALSE}
#first import the data
mrot_tib <- readr::read_csv("data/mentalrotation.csv", na = "NA")

# now make sure the columns we want as nominal vals are treated as nominal, using forcats::as_factor()
mrot_tib <- mrot_tib %>% dplyr::mutate(
  DesiredResponse = forcats::as_factor(DesiredResponse),
  ActualResponse = forcats::as_factor(ActualResponse),
  CorrectResponse = forcats::as_factor(CorrectResponse),
  Sex = forcats::as_factor(Sex),
)

# first group by Participant and store in a new tibble
mrot_bysub <- mrot_tib %>% drop_na(Time) %>% 
  group_by(Participant) %>% 
  dplyr::summarise(
    sub_meanRT = mean(Time)
  )
# then average across Participants
mrot_bysub %>% dplyr::summarise(
  meanRT = mean(sub_meanRT),
  ci.low = ggplot2::mean_cl_normal(sub_meanRT)$ymin,
  ci.upp = ggplot2::mean_cl_normal(sub_meanRT)$ymax,
  median =  median(sub_meanRT),
  sd = sd(sub_meanRT),
  cases = n() - sum(is.na(sub_meanRT))
) %>% 
    knitr::kable(caption = "Response Time Descriptives", digits = 3) %>% 
    kableExtra::kable_styling(full_width = FALSE)

# now visualize the distribution
p1 <- mrot_bysub %>% drop_na(sub_meanRT) %>%
    ggplot( aes(x=sub_meanRT)) + geom_histogram(binwidth=100) + theme_classic() +
        labs (title = "Response Time distribution")
p2 <- mrot_bysub %>% drop_na(sub_meanRT) %>%
    ggplot( aes(y=sub_meanRT)) + geom_boxplot() + theme_classic() + 
        labs (title = "Response Time box plot")
p3 <- mrot_bysub %>% drop_na(sub_meanRT) %>%
    ggplot( aes(sample=sub_meanRT)) + geom_qq() + geom_qq_line() + theme_classic() +
        labs (title = "Response Time Q-Q")
p1
p2
p3
mrot_bysub %>% {shapiro.test(.$sub_meanRT)}
```
</div>
  
------------------------------------------------------------------------

## Step 3 - more things  
- Notes  

#### header

<button class="btn btn-primary" data-toggle="collapse" data-target="#step-5"> Show/Hide Solution </button>  
<div id="step-5" class="collapse">  
```{r Step5-scatter,fig.show='hold', results='hold'}
p1 <- mrot_bysub %>% 
  ggplot(aes(x = sub_accuracy, y = sub_meanRT)) + 
    geom_point(stat="identity") +
    stat_smooth(method = "lm", formula = "y ~ x", se = FALSE) + #intercept automatically included
    coord_cartesian(ylim = c(0, 6000), xlim = c(.6,1)) + 
    theme_classic() + labs(title="scatter", y = "mean response time (ms)", x = "accuracy")
p1
```
</div>

------------------------------------------------------------------------

## Challenge: For your reference (or if you have extra time in lab) - here are some alternative approaches to visualizing variability.  

Some journals (e.g., ["Kick the bar chart habit" | *Nature Methods*](https://doi.org/10.1038/nmeth.2837)) have started to discourage plots that don't show data variability well. Here are some alternatives you can use:
  
#### 1. Use a box plot instead of plotting means:  
- a box plot shows:  
  - the median (line)  
  - a box spanning the interquartile range (IQR=25th to 75th percentile)  
  - "whiskers" extending 1.5*(IQR) past the box edges
  - points for individual extreme values beyond the whiskers 
- notice that we have to re-specify the x-axis (Angle) variable as a factor to get geom_boxplot to work correctly `mutate(Angle=forcats::as_factor(Angle))`  
- notice that we pass in subject level means, instead of group means  
- also notice that we have to expand the ylim range to see all outliers  
  
<button class="btn btn-primary" data-toggle="collapse" data-target="#vis6-1"> Show/Hide Code and Plot </button>  
<div id="vis6-1" class="collapse">  
```{r Step6.1-boxplot-grouped, fig.show='hold', results='hold', message=FALSE}
# regroup data 
mrot_bysub <- mrot_tib %>% mutate(Angle=forcats::as_factor(Angle)) %>% drop_na(Time) %>% 
  group_by(Participant, Angle, DesiredResponse) %>% 
  dplyr::summarise(
    sub_meanRT = mean(Time)
  )

p1 <- mrot_bysub %>% 
  ggplot(aes(x = Angle, y = sub_meanRT, fill=DesiredResponse)) + 
    geom_boxplot() +
    coord_cartesian(ylim = c(0, 6000)) + 
    theme_classic() + labs(title="Response time grouped box plot", y = "mean response time (ms)", x = "angle of disparity (degrees)")
p1
```
</div>
  
----------------------------------------------------------------------------
